# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scrapy General Point

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Install dependencies with poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry install

    - name: Run Scrapy Crawlers
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        poetry run python3 JobsCrawlerProject/00_main_run_crawlers.py


